# config/custom_od.yaml
# Parameters for Custom Object Detection component

---
/**:
    ros__parameters:

      general:
        main_node_name: 'zed_node'
        detection_topic: 'detections'
        loop_frequency: 150.0
